//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A2_HTML5_Biz_App_New.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerPropertyDescription
    {
        public int OwnerPropertyId { get; set; }
        public string PropertyType { get; set; }
        public int OwnerId { get; set; }
        public string Address { get; set; }
        public int BedRoomNo { get; set; }
        public int TotalRooms { get; set; }
        public int PropertyBuildupArea { get; set; }
        public string PropertyDescription { get; set; }
        public string PropertySaleRentStatus { get; set; }
        public int SaleOrRentCost { get; set; }
        public int PropertyAge { get; set; }
        public string Status { get; set; }
        public System.DateTime RegistrationDate { get; set; }
    
        public virtual OwnerInfo OwnerInfo { get; set; }
    }
}
